### ISSUE TITLE
NULL the username when removing the user  / user credentials

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-webflow#1323]
When a user or his credentials are removed, his username in credentials remains in the database with the status `REMOVED`. This prevents to create a new user with the same username. 

Set username to NULL when the user or his credentials are removed (the original value of the username should be retained in audit and credential history)

**Comment by kopovan** [comment]
After deleting user the column `user_name` is setup to `NULL` in table `ns_credential_storage`. Also afterwards it is possible to create a new user with the same username.
<img src="https://github.com/wultra/powerauth-webflow/assets/135111051/a2141459-4acc-4b25-ba32-3ad8cdeb78a8" width="300" />
<img src="https://github.com/wultra/powerauth-webflow/assets/135111051/a8b2a028-9871-475b-b50d-b34c626d2c4f" width="300" />

TBD: I need to solve issue on my side with logging in to [authentication](http://localhost:13030/powerauth-webflow/oauth/authorize?client_id=democlient&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fpowerauth-webflow-client%2Fconnect%2Fdemo&scope=aisp&response_type=code) (OTP is not generating to `ns_otp_storage` table).

TC1: after deleting user it should not be possible to do successful authentication
TC2: If the user is active authentication is successful
TC3: it is not possible to create another user with the same username

Based on this issue I have also added a new collection Webflow to Postman.

**Comment by kopovan** [comment]
As discussed with @zcgandcomp authorization cannot be finished because of data adapter. OTP code is being generated into a table `da_sms_authorization`. We can close the task in Wultra Backlog and we will test this later.
