### ISSUE TITLE
SMS OTP confirmation button remains enabled after error

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-webflow#1343]
Step to reproduce:
Navigate to the login sca SMS form.
Enter an invalid password and OTP.
Wait for the error message from the backend.
Password and OTP values are reset.

Expected result:
Button Sign In (confirmation) is disabled

Actual result:
Button Sign In (confirmation) is enabled

**Comment by kopovan** [comment]
After entering a wrong pwd and SMS code I get an error msg "User authentication failed". After filling in the fields the button "Sign in" is enabled again.

![image](https://github.com/wultra/powerauth-webflow/assets/135111051/0d736e9e-65ab-4a2f-989d-a830fb196c89)
