### ISSUE TITLE
The entered credentials are removed upon submit

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-webflow#1363]
The user enters his credentials (password and OTP)  and press confirm

Expected behavior:
Show loading spinner
Show either a successful result or a reseted form and error message.
 
Actual behavior:
The password and OTP are immediately removed.

Note 
In smsComponent.js the `handleSubmit` function set empty values of password and OTP into the state. This should be done after the `smsAuthAction.authenticate` dispatch an error

**Comment by kopovan** [comment]
1. If I enter a wrong pwd and otp code the form is cleared (except login number) and error msg displayed
2. After hitting the "Sign in" button the load spinner is showed
3. If I enter a correct credentials I am successfuly transfered to the next screen
