### ISSUE TITLE
OTP Confirmation button is not disabled after confirmation allowing multiple submitts.

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-webflow#1375]
The scenario:
User enter OTP and Password.
User hit the Confirmation button.

Expected result:
User cannot click on the Confirmation button again.

Actual result:
User can click on the Confirmation button several times - error on the subsequent click.

**Comment by banterCZ** [comment]
Fixed in #1343

**Comment by kopovan** [comment]
Right after clicking the "Sign in" button, the button is disabled (screenshot for a screen reference)
![image](https://github.com/wultra/powerauth-webflow/assets/135111051/2daecfec-eae3-4ed2-9fbd-48ae0f751978)
