### ISSUE TITLE
Executable war

### ISSUE THREAD

**Issue by banterCZ** [wultra/powerauth-webflow#1457]
Add embedded tomcat as the provided dependency (to be part of `WEB-INF/lib-provided` but not `lib`) and make it possible to run it via `java -jar`.

**Comment by jnpsk** [comment]
This one runs just fine with the standalone profile on.
- parent pom has `org.apache.tomcat.embed:*:*:*:compile` banned

Each component {powerauth-nextstep, powerauth-tpp-engine, powerauth-webflow, powerauth-webflow-client}:
- java -jar executable iff the standalone profile is active
- tomcat in scope provided iff the standalone profile is active, excluded from transitive dependencies

**Comment by jandusil** [comment]
@jnpsk cc @banterCZ  We are getting rid of the standalone profile. The issue is still relevant

**Comment by jandusil** [comment]
I will take it
