### ISSUE TITLE
Add support for bcrypt to store the password

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-webflow#1717]
Currently when we re using hashing for the protection of stored password only Argon is available. We need to support also bcrypt.

**Comment by zcgandcomp** [comment]
- set up hashing policy for credentials for usage bcrypt.
- create credential for a user.
- try authenticate.

**Comment by romanstrobl** [comment]
Here are instructions for testing.

1. Create an application in Next Step for testing, e.g.:

curl --request POST \
  --url http://localhost:8080/powerauth-nextstep/application \
  --header 'Content-Type: application/json' \
  --data '{
  "requestObject": {
    "applicationName": "test_app",
    "description": null
  }
}'

2. Create an organization for testing, e.g.

curl --request POST \
  --url http://localhost:8080/powerauth-nextstep/organization \
  --header 'Content-Type: application/json' \
  --data '{
  "requestObject": {
    "organizationId": "test_org",
    "displayNameKey": null,
    "orderNumber": 1,
    "defaultCredentialName": null,
    "defaultOtpName": null,
    "default": true
  }
}'

3. Create a hashing configuration for bcrypt:

curl --request POST \
  --url http://localhost:8080/powerauth-nextstep/hashconfig \
  --header 'Content-Type: application/json' \
  --data '{
  "requestObject": {
    "hashConfigName": "bcrypt",
    "algorithm": "BCRYPT",
    "parameters": {
    }
  }
}'

4. Create a credential policy, e.g.:
curl --request POST \
  --url http://localhost:8080/powerauth-nextstep/credential/policy \
  --header 'Content-Type: application/json' \
  --data '{
  "requestObject": {
    "credentialPolicyName": "test_policy",
    "description": "test policy",
    "usernameLengthMin": 8,
    "usernameLengthMax": 20,
    "usernameAllowedPattern": null,
    "credentialLengthMin": 8,
    "credentialLengthMax": 20,
    "limitSoft": 5,
    "limitHard": 10,
    "checkHistoryCount": 0,
    "rotationEnabled": false,
    "rotationDays": null,
    "temporaryCredentialExpirationTime": null,
    "usernameGenAlgorithm": "NO_USERNAME",
    "usernameGenParam": {
      "length": 10
    },
    "credentialGenAlgorithm": "RANDOM_PASSWORD",
    "credentialGenParam": {
      "length": 10,
      "includeSmallLetters": true,
      "smallLettersCount": 4,
      "includeCapitalLetters": true,
      "capitalLettersCount": 2,
      "includeDigits": true,
      "digitsCount": 2,
      "includeSpecialChars": true,
      "specialCharsCount": 2
    },
    "credentialValParam": {
      "includeWhitespaceRule": true,
      "includeUsernameRule": true,
      "includeAllowedCharacterRule": false,
      "allowedChars": null,
      "includeAllowedRegexRule": false,
      "allowedRegex": null,
      "includeIllegalCharacterRule": false,
      "illegalChars": null,
      "includeIllegalRegexRule": false,
      "illegalRegex": null,
      "includeCharacterRule": false,
      "includeSmallLetters": false,
      "smallLettersMin": 0,
      "includeCapitalLetters": true,
      "capitalLettersMin": 2,
      "includeAlphabeticalLetters": true,
      "alphabeticalLettersMin": 4,
      "includeDigits": true,
      "digitsMin": 2,
      "includeSpecialChars": true,
      "specialCharsMin": 2
    }
  }
}'

5. Create a credential definition, e.g.:

curl --request POST \
  --url http://localhost:8080/powerauth-nextstep/credential/definition \
  --header 'Content-Type: application/json' \
  --data '{
  "requestObject": {
    "credentialDefinitionName": "test_credential",
    "applicationName": "test_app",
    "organizationId": "test_org",
    "credentialPolicyName": "test_policy",
    "description": null,
    "category": "PASSWORD",
    "encryptionEnabled": false,
    "encryptionAlgorithm": "NO_ENCRYPTION",
    "hashingEnabled": true,
    "hashConfigName": "bcrypt",
    "e2eEncryptionEnabled": false,
    "e2eEncryptionAlgorithm": null,
    "e2eEncryptionCipherTransformation": null,
    "e2eEncryptionForTemporaryCredentialEnabled": false,
    "dataAdapterProxyEnabled": false
  }
}'

6. Create a user in Next Step, e.g.:

curl --request POST \
  --url http://localhost:8080/powerauth-nextstep/user \
  --header 'Content-Type: application/json' \
  --data '{
  "requestObject": {
    "userId": "test_user",
    "extras": {
    },
    "roles": [
    ],
    "contacts": [
    ],
    "credentials": [
      {
        "credentialName": "test_credential",
        "credentialType": "PERMANENT",
        "username": "user12345",
        "credentialValue": "test",
        "timestampExpires": "2024-12-23T11:12:15.771Z",
        "validationMode": "NO_VALIDATION",
        "credentialHistory": [
        ]
      }
    ]
  }
}'

Now we can verify in database that the credential is hashed using bcrypt in table ns_credential_storage in column value e.g.:

$2a$10$ShcJCDpNh.irJNr8W9BFHewKb8fYY1Bh8B1qZh.eUeI0ACsu9LgoC

7. Authenticate a user, e.g.:
curl --request POST \
  --url http://localhost:8080/powerauth-nextstep/auth/credential \
  --header 'Content-Type: application/json' \
  --data '{
  "requestObject": {
    "credentialName": "test_credential",
    "userId": "test_user",
    "credentialValue": "test",
    "authenticationMode": "MATCH_EXACT",
    "credentialPositionsToVerify": [
    ],
    "operationId": null,
    "updateOperation": false,
    "authMethod": null
  }
}
'

The result should be "authenticationResult": "SUCCEEDED".

In case the password is incorrect, the result should be "authenticationResult": "FAILED".

**Comment by romanstrobl** [comment]
@korbelm we need to deploy the war file before testing, but the job is failing:

https://github.com/wultra/powerauth-webflow/actions/runs/11459555118/job/31884301888

Any idea?

**Comment by banterCZ** [comment]
I will deploy it manually. The GHA behavior looks strange, it should work.

**Comment by kopovan** [comment]
TEST OK, test report below.

Create an application in Next Step for testing:
```
curl -X 'POST' \
  'https://powerauth-dev.westeurope.cloudapp.azure.com/powerauth-nextstep/application' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "requestObject": {
    "applicationName": "blueMoon",
    "description": null
  }
}'
```

Response body
```
{
  "status": "OK",
  "responseObject": {
    "applicationName": "blueMoon",
    "applicationStatus": "ACTIVE",
    "description": null
  }
}
```

Create an organization for testing:
```
curl -X 'POST' \
  'https://powerauth-dev.westeurope.cloudapp.azure.com/powerauth-nextstep/organization' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "requestObject": {
    "organizationId": "test_org",
    "displayNameKey": null,
    "orderNumber": 1,
    "defaultCredentialName": null,
    "defaultOtpName": null,
    "default": true
  }
}'
```

Response body
```
{
  "status": "OK",
  "responseObject": {
    "organizationId": "test_org",
    "displayNameKey": null,
    "orderNumber": 1,
    "defaultCredentialName": null,
    "defaultOtpName": null,
    "default": true
  }
}
```

Create a hashing configuration for bcrypt:
```
curl -X 'POST' \
  'https://powerauth-dev.westeurope.cloudapp.azure.com/powerauth-nextstep/hashconfig' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "requestObject": {
    "hashConfigName": "bcrypt",
    "algorithm": "BCRYPT",
    "parameters": {}
  }
}'

```
Response body
```
{
  "status": "OK",
  "responseObject": {
    "hashConfigName": "bcrypt",
    "algorithm": "BCRYPT",
    "parameters": {},
    "hashConfigStatus": "ACTIVE"
  }
}
```

Create a credential policy:
```
curl -X 'POST' \
  'https://powerauth-dev.westeurope.cloudapp.azure.com/powerauth-nextstep/credential/policy' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
"requestObject": {
"credentialPolicyName": "test_policy",
"description": "test policy",
"usernameLengthMin": 8,
"usernameLengthMax": 20,
"usernameAllowedPattern": null,
"credentialLengthMin": 8,
"credentialLengthMax": 20,
"limitSoft": 5,
"limitHard": 10,
"checkHistoryCount": 0,
"rotationEnabled": false,
"rotationDays": null,
"temporaryCredentialExpirationTime": null,
"usernameGenAlgorithm": "NO_USERNAME",
"usernameGenParam": {
"length": 10
},
"credentialGenAlgorithm": "RANDOM_PASSWORD",
"credentialGenParam": {
"length": 10,
"includeSmallLetters": true,
"smallLettersCount": 4,
"includeCapitalLetters": true,
"capitalLettersCount": 2,
"includeDigits": true,
"digitsCount": 2,
"includeSpecialChars": true,
"specialCharsCount": 2
},
"credentialValParam": {
"includeWhitespaceRule": true,
"includeUsernameRule": true,
"includeAllowedCharacterRule": false,
"allowedChars": null,
"includeAllowedRegexRule": false,
"allowedRegex": null,
"includeIllegalCharacterRule": false,
"illegalChars": null,
"includeIllegalRegexRule": false,
"illegalRegex": null,
"includeCharacterRule": false,
"includeSmallLetters": false,
"smallLettersMin": 0,
"includeCapitalLetters": true,
"capitalLettersMin": 2,
"includeAlphabeticalLetters": true,
"alphabeticalLettersMin": 4,
"includeDigits": true,
"digitsMin": 2,
"includeSpecialChars": true,
"specialCharsMin": 2
}
}
}'
```

Response body
`{   "status": "OK",   "responseObject": {     "credentialPolicyName": "test_policy",     "description": "test policy",     "credentialPolicyStatus": "ACTIVE",     "usernameLengthMin": 8,     "usernameLengthMax": 20,     "usernameAllowedPattern": null,     "credentialLengthMin": 8,     "credentialLengthMax": 20,     "limitSoft": 5,     "limitHard": 10,     "checkHistoryCount": 0,     "rotationEnabled": false,     "rotationDays": null,     "temporaryCredentialExpirationTime": null,     "usernameGenAlgorithm": "NO_USERNAME",     "usernameGenParam": {       "length": 10     },     "credentialGenAlgorithm": "RANDOM_PASSWORD",     "credentialGenParam": {       "length": 10,       "includeSmallLetters": true,       "smallLettersCount": 4,       "includeCapitalLetters": true,       "capitalLettersCount": 2,       "includeDigits": true,       "digitsCount": 2,       "includeSpecialChars": true,       "specialCharsCount": 2     },     "credentialValParam": {       "includeWhitespaceRule": true,       "includeUsernameRule": true,       "includeAllowedCharacterRule": false,       "allowedChars": null,       "includeAllowedRegexRule": false,       "allowedRegex": null,       "includeIllegalCharacterRule": false,       "illegalChars": null,       "includeIllegalRegexRule": false,       "illegalRegex": null,       "includeCharacterRule": false,       "includeSmallLetters": false,       "smallLettersMin": 0,       "includeCapitalLetters": true,       "capitalLettersMin": 2,       "includeAlphabeticalLetters": true,       "alphabeticalLettersMin": 4,       "includeDigits": true,       "digitsMin": 2,       "includeSpecialChars": true,       "specialCharsMin": 2     }   } }`

Create a credential definition:
```
curl -X 'POST' \
  'https://powerauth-dev.westeurope.cloudapp.azure.com/powerauth-nextstep/credential/definition' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
"requestObject": {
"credentialDefinitionName": "test_credential",
"applicationName": "blueMoon",
"organizationId": "test_org",
"credentialPolicyName": "test_policy",
"description": null,
"category": "PASSWORD",
"encryptionEnabled": false,
"encryptionAlgorithm": "NO_ENCRYPTION",
"hashingEnabled": true,
"hashConfigName": "bcrypt",
"e2eEncryptionEnabled": false,
"e2eEncryptionAlgorithm": null,
"e2eEncryptionCipherTransformation": null,
"e2eEncryptionForTemporaryCredentialEnabled": false,
"dataAdapterProxyEnabled": false
  }
}'
```

Response body
`{   "status": "OK",   "responseObject": {     "credentialDefinitionName": "test_credential",     "applicationName": "blueMoon",     "credentialPolicyName": "test_policy",     "description": null,     "category": "PASSWORD",     "encryptionEnabled": false,     "encryptionAlgorithm": "NO_ENCRYPTION",     "hashingEnabled": true,     "hashConfigName": "bcrypt",     "e2eEncryptionEnabled": false,     "e2eEncryptionAlgorithm": null,     "e2eEncryptionCipherTransformation": null,     "e2eEncryptionForTemporaryCredentialEnabled": false,     "credentialDefinitionStatus": "ACTIVE",     "dataAdapterProxyEnabled": false   } }`

Create a user in Next Step:
```
curl -X 'POST' \
  'https://powerauth-dev.westeurope.cloudapp.azure.com/powerauth-nextstep/user' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
"requestObject": {
"userId": "test_user",
"extras": {
},
"roles": [
],
"contacts": [
],
"credentials": [
{
"credentialName": "test_credential",
"credentialType": "PERMANENT",
"username": "user12345",
"credentialValue": "test",
"timestampExpires": "2024-12-23T11:12:15.771Z",
"validationMode": "NO_VALIDATION",
"credentialHistory": [
]
}
]
}
}
```
Response body
`{   "status": "OK",   "responseObject": {     "userId": "test_user",     "userIdentityStatus": "ACTIVE",     "extras": {},     "roles": [],     "contacts": [],     "credentials": [       {         "credentialName": "test_credential",         "credentialType": "PERMANENT",         "credentialStatus": "ACTIVE",         "username": "user12345",         "credentialValue": null,         "credentialChangeRequired": true,         "timestampCreated": "2024-10-25T12:41:45.525+00:00",         "timestampLastUpdated": null,         "timestampBlocked": null,         "timestampExpires": "2024-12-23T11:12:15.771+00:00",         "timestampLastCredentialChange": "2024-10-25T12:41:45.525+00:00",         "timestampLastUsernameChange": "2024-10-25T12:41:45.525+00:00"       }     ]   } }`


Now we can verify in database that the credential is hashed using bcrypt in table ns_credential_storage in column value e.g.:

$2a$10$xBfArG50eGNaY4HlunAVKuEG3ZH0a17w4VVH8k5equgoVg4ALDu5W

![Image](https://github.com/user-attachments/assets/2ff35826-ec23-43dc-b5c3-527ed7142484)


Authenticate a user:
```
curl -X 'POST' \
  'https://powerauth-dev.westeurope.cloudapp.azure.com/powerauth-nextstep/auth/credential' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
"requestObject": {
"credentialName": "test_credential",
"userId": "test_user",
"credentialValue": "test",
"authenticationMode": "MATCH_EXACT",
"credentialPositionsToVerify": [
],
"operationId": null,
"updateOperation": false,
"authMethod": null
}
}'
```

The result should be "authenticationResult": "SUCCEEDED".:
Response body
```
{
  "status": "OK",
  "responseObject": {
    "userId": "test_user",
    "userIdentityStatus": "ACTIVE",
    "timestampBlocked": null,
    "credentialStatus": "ACTIVE",
    "credentialChangeRequired": true,
    "authenticationResult": "SUCCEEDED",
    "remainingAttempts": 5,
    "showRemainingAttempts": false,
    "errorMessage": null,
    "operationFailed": false
  }
}
```

In case the password is incorrect, the result should be "authenticationResult": "FAILED".

```
{
  "status": "OK",
  "responseObject": {
    "userId": "test_user",
    "userIdentityStatus": "ACTIVE",
    "timestampBlocked": null,
    "credentialStatus": "ACTIVE",
    "credentialChangeRequired": true,
    "authenticationResult": "FAILED",
    "remainingAttempts": 4,
    "showRemainingAttempts": false,
    "errorMessage": null,
    "operationFailed": false
  }
}
```
