### ISSUE TITLE
Separate Form Data model class for create operation request in Next Step

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-webflow#389]
It is currently non-trivial to create an operation using Next Step REST API because the generic OperationFormData class is used to model form data. Many of the fields which are sent in the form data when operation is created are null. It is hard to figure out the meaning of some of the unecessary fields.

We should create a separate model class for FormData which is used in Next Step API when operation is created. The create operation step is important for integration as well as testing and should be simpler.

**Comment by petrdvorak** [comment]
This one can wait for the next release.

**Comment by romanstrobl** [comment]
Closing issue.
