### ISSUE TITLE
Add NOT NULL constraints to DDL

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-webflow#404]
The current DDL does not contain NOT NULL constraints. We should add these constraints at least for new deployments to improve database consistency.

**Comment by petrdvorak** [comment]
@romanstrobl Isn't this already fixed with the other changes we made in DDL files?

**Comment by romanstrobl** [comment]
Not yet, I was only fixing PowerAuth server DDL.

**Comment by petrdvorak** [comment]
OK. However, this fix can wait for the next release.
