### ISSUE TITLE
Enable PARTY_INFO attribute for mobile API

### ISSUE THREAD

**Issue by kober32** [wultra/powerauth-webflow#422]
Send proper `PARTY_INFO` for mobile API instead of KEY_VALUE as it is in 2018.06.

**Comment by romanstrobl** [comment]
Note to self:
https://github.com/wultra/powerauth-webflow/blob/develop/powerauth-webflow-authentication-mtoken/src/main/java/io/getlime/security/powerauth/lib/webflow/authentication/mtoken/model/converter/AttributeConverter.java#L51
