### ISSUE TITLE
Date time format in operations list response attributes is not ISO-8601 compliant

### ISSUE THREAD

**Issue by TomasKypta** [wultra/powerauth-webflow#432]
[List pending operations](https://github.com/wultra/powerauth-webflow/wiki/Next-Step-Server-REST-API-Reference#list-pending-operations) contains date time formats that are not ISO-8601 compliant.
The bug is in time zone designator.
The API returns "2018-09-04T09:20:37+0000" which is incorrect,
a correct value would be e.g. "2018-09-04T09:20:37+00:00".

> Zone-offset	may	be	omitted	or	included.		Time	zone	designation	consists	of	either	a	'Z'	to	indicate	UTC,	
> or	a	'+'	or	'-'	to	indicate	"ahead	of	UTC"	or	"behind	UTC",	followed	by	a	2-digit	hour,	followed	optionally	
> by	a	colon	and	the	2-digit	minutes.

**Comment by petrdvorak** [comment]
The ISO 8601 allows encoding the timezone without a colon. The specification from W3 is not authoritative in this aspect, and the definitions do vary:

> So if the time being described is one hour ahead of UTC (such as the time in Berlin during the winter), the zone designator would be "+01:00", "+0100", or simply "+01".

 -- https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC

Spring (or rather Jackson Data Binding that is under the hood) uses a default format without the colon.
