### ISSUE TITLE
Enable consent screen and allow customization

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-webflow#461]
Currently, we skip the consent screen. We should allow adding the consent screen back (either using a default OAuth 2.0 consent screen or - more likely - by implementing our own).

The consent screen should allow content customization (display the third party provider info, such as name, app name, company ID, or display the operation attributes) via Data Adapter.

**Comment by petrdvorak** [comment]
To be able to render the consent screen correctly, we need to have a piece of information about the application that requested the consent. In order to be able to do this, we need to be able to assign application context to `createOperation` and `updateOperation` methods on NextStep server:

```json
"application": {
    "id": "abc123", // app ID for unique lookup
    "name": "Bankovní vizitka", // app name
    "description": "Snadné ověření identity pomocí účtu v bance", // description
    "extras": { // any cystome data
         "_requestedScopes": [ "KYC", "OAUTH" ] // example: original scopes requested
    }
}
```

**Comment by romanstrobl** [comment]
The application context model has changed a bit after discussion:
```
{
    "application": {
        "id": "abc123", // app ID for unique lookup
        "name": "Bankovní vizitka", // app name
        "description": "Snadné ověření identity pomocí účtu v bance", // description
        "extras": { // any custom data
             "requestedScopes": [ "KYC", "OAUTH" ] // example: original scopes requested
             "applicationOwner": "BankABC"
        }
    }
}
```
