### ISSUE TITLE
Generify POST for PUT calls

### ISSUE THREAD

**Issue by saalistaja** [wultra/powerauth-webflow#560]
When the PUT method is forbidden on client side we are bypassing that by providing a `POST` variant with `/update` suffix endpoint path.

Currently we have to provide this approach manually for all our endpoints directly in the code.

It would be nice to generify the approach on filter layer or using some clever routing approach:
* all `POST` calls to `/update` remap to `PUT` call
* one place instead many special bypass methods needed in the code

**Comment by petrdvorak** [comment]
Let’s not do this - I find this to be an antipattern with many disadvantages, such as:

- Swagger won’t pick these endpoints
- We will not see the endpoints in code
