### ISSUE TITLE
At least one redirect_uri must be registered with the client

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-webflow#653]
After recent upgrade of Spring OAuth 2 integration we need to configure the `web_server_redirect_uri` parameter for the client.

See error:
```
Handling OAuth2 error: error="invalid_request", error_description="At least one redirect_uri must be registered with the client."
```

**Comment by petrdvorak** [comment]
I added a comment to spring-projects/spring-security-oauth#1656, it is pity they don't allow the regexp for this...

**Comment by romanstrobl** [comment]
Yes, the implementation seems rather naive.

**Comment by petrdvorak** [comment]
@romanstrobl On the other hand, OAuth 2.0 specs ask for an exact match so I do get them...
