### ISSUE TITLE
Broken build after Snyk update

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-webflow#776]
The following error occurs during build: https://github.com/snyk/snyk/issues/991 after applying latest Snyk patch.

Damn, Snyk, don't break our builds!

**Comment by orkamara** [comment]
@romanstrobl - which version of Snyk do you use? can you try to reinstall Snyk and let us know if the issue still exists?

**Comment by romanstrobl** [comment]
Version `1.290.1` broke the build. Reverting to `1.278.2` resolved the issue.

**Comment by romanstrobl** [comment]
The issue goes away after removing `node_modules` and doing a completely clean build. Closing issue.

**Comment by orkamara** [comment]
Happy the issues was solved - thanks for letting us know @romanstrobl :)
