### ISSUE TITLE
Disable confirmation buttons on empty values

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-webflow#811]
Currently, we allow submitting the forms even if the username, password, or SMS OTP fields are empty. To improve the user experience, we should disable the submit button until the user fills in all required fields.

**Comment by romanstrobl** [comment]
I assume we will also add such behaviour to the offline QR code screen, consent screen and any other screen with user input.

**Comment by petrdvorak** [comment]
@romanstrobl Good point, yes.
