### ISSUE TITLE
Consider using Spring Data JPA Streams for queries with many results

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-webflow#985]
Currently, we sometimes have calls like this in the code:

```java
credentialRepository.findAllByStatus(CredentialStatus.ACTIVE);
```

This will make JVM explode since all results will be fetched and in memory at once. Paging would help, but why suffer when there are Streams...

https://www.baeldung.com/spring-data-java-8

**Comment by romanstrobl** [comment]
I fixed the `credentialRepository.findAllByStatus()` call to use `JPQL` with a `@Modifying` `UPDATE` query and avoid retrieving the data at all into the application.

I went through the code and we can apply the streaming API to:
- `lookupUsers` -- the record count depends on the request, the `findAllByCredentialDefinitionAndStatus` method is problematic
- `updateUsers` -- the record count depends on the request, the issue can be avoided by using smaller requests
- `getUserAuthenticationList` -- the record count depends on the request, the issue can be avoided by using smaller date range
- `removeAllOtps` -- the record count should be in hundreds or thousands in the worst case)

The rest of `findAll` repository calls does not return more than 100 results.
